{% set name = "animatplot" %}
{% set version = "0.4.3" %}
{% set sha256 = "a720b144637768ba55df9ce3d576a7a3b87c24674e94edad5b91b39f4093dcfd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - matplotlib >=2.2

test:
  imports:
    - animatplot
    - animatplot.blocks
    - animatplot.animations

about:
  home: https://github.com/t-makaro/animatplot/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Animating plots with matplotlib made easy

  description: |
    animatplot is build to make it as easy to produce an animated plot
    as easy as it is to make a static plot.
  doc_url: https://animatplot.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - t-makaro
