travis:
  secure:
    BINSTAR_TOKEN: qMdOEkC0frHf6ue236dGoA8StHU18X6ww4JMt7qtGyBgjhm+rw3RlOeRhcRI0bXZ/90rlsHX1aHDUCO7EZinGaW6Cxp9olG5LeSvqo0f0MReyhHZA6SfrczKyYoF/QWF9PChMeJSuQ9JXLoKepNzQRN6IPwzwZZ70lWzkZQiSsFX0v7BM2tckMzECgEofR7UeWdAEW9DxUKkeoJdKaTBmM6+47lWIIsk30XETFgA86fnqGIMQ6rbn0LU1866uttqCytPMsFJpl4vCi+Q3zWT9yQlwmPK/pi4dxQL7HTuTxiHuVjAaUrPi0wN71ei7vfOTsdzOla1JePfPdEf5Js3Ugl0WRgLgcXrOfxEhO8ea7SDxMmrQhqCBxnqko+S8MhEe4Qkr3/uttUKtme5XYom2sNWW9DAuxC5fMxvfp03pMvo/i2hofcoh9uZ93x7ArfBOsAL7bxYIg5jbQWHjg2U8k4gE9pV2+Wm7Rn5Q+IANUSLT+okox9JP/njpGyp2Zkt4rpVf0xd7urulEBaRFS4juJ8e2nnhoFdvgl96258V0Rm6eQ9G1MtlsXf1w+/k66ffjCq67TQyPqtHBcn7uUiW6lP7BxAiZRVd0HFOzadgamLpbJ9R9rKRel9kPit51Z+hwYDqwW81uuBHL3Raxd53b6wy58sVLjKwc5kNX6hZGo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
